### PR TITLE
Adjust whitespace after semicolons to fix tests

### PR DESCRIPTION
**Pull request by johnmichel**

### CODE REVIEW

**Comment by devinivy** [comment]
Might be worth upgrading to lab 6 at the same time!  Mind bumping that lab version and performing any leftover linting?

**Comment by johnmichel** [comment]
@devinivy Sure!  I'll have something ready soon.

**Comment by johnmichel** [comment]
@devinivy Everything should be good to go now

**Comment by devinivy** [comment]
Looks good, thanks again!  It will be nice to see the build badge green.  Any reason you had to include `eslint-config-hapi`, though?  I think it should only be necessary if you want to extend that eslint config.  If it's not required, could you just remove it?

@hueniverse want to push the button?

**Comment by johnmichel** [comment]
The issue that I ran into after bumping `lab` up to `6.x.x` was this:

```
09:13:11 ~/Projects/GitHub/nigel (master) @ d1493a6 john$ npm test

> nigel@1.0.1 test /Users/john/Projects/GitHub/nigel
> lab -a code -t 100 -L


  
  ......................../Users/john/Projects/GitHub/nigel/node_modules/eslint/lib/config.js:209
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-hapi'
Referenced from: /Users/john/Projects/GitHub/nigel/node_modules/lab/lib/linters/eslint/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readConfigFromFile (/Users/john/Projects/GitHub/nigel/node_modules/eslint/lib/config.js:151:44)
    at loadConfig (/Users/john/Projects/GitHub/nigel/node_modules/eslint/lib/config.js:172:22)
    at /Users/john/Projects/GitHub/nigel/node_modules/eslint/lib/config.js:203:46
    at Array.reduceRight (native)
    at loadConfig (/Users/john/Projects/GitHub/nigel/node_modules/eslint/lib/config.js:187:36)
    at new Config (/Users/john/Projects/GitHub/nigel/node_modules/eslint/lib/config.js:381:38)
```

After I added `eslint-config-hapi`, the error went away and the tests began to pass again, so I figured it necessary to include it.

**Comment by devinivy** [comment]
I'll look into it!

**Comment by devinivy** [comment]
Ah, is it possible you were linting with a global install of lab?

**Comment by johnmichel** [comment]
Nope, I only had `lab` installed locally.

**Comment by devinivy** [comment]
@johnmichel I checked-out your branch, removed eslint-config-hapi from devDependencies, installed, then ran the tests, and all worked great.  Could you perhaps try removing that dependency and performing a fresh install/test on your end.  Sorry this simple change became complicated.  Seeing the "passing" badge at the end of this rigmarole ought to pay off.

**Comment by johnmichel** [comment]
@devinivy Not sure how I got into that funky state, but removing the `eslint-config-hapi` and doing a fresh install + test with the upgraded `lab` version worked perfectly.  Thanks for the recommendation on that one :+1:

**Comment by devinivy** [comment]
Looks good to me.  @hueniverse wanna make the final call as lead maintainer?  I notice this repo is not on the list for lead maintainer takeover (https://github.com/hapijs/contrib/issues/33).  As an ancillary question, is there any interest in passing this repo off to someone?  It hasn't gotten any love for a little while.

**Pull request merged**
